// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: replication.proto

package replpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	NodeId           string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CreatedAt        *timestamp.Timestamp     `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DnsRecords       []*DNSRecord             `protobuf:"bytes,3,rep,name=dns_records,json=dnsRecords,proto3" json:"dns_records,omitempty"`
	DomainEntries    []*DomainEntryProjection `protobuf:"bytes,4,rep,name=domain_entries,json=domainEntries,proto3" json:"domain_entries,omitempty"`
	SnapshotRecordId uint64                   `protobuf:"varint,5,opt,name=snapshot_record_id,json=snapshotRecordId,proto3" json:"snapshot_record_id,omitempty"`
	Last             bool                     `protobuf:"varint,6,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Snapshot) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Snapshot) GetDnsRecords() []*DNSRecord {
	if x != nil {
		return x.DnsRecords
	}
	return nil
}

func (x *Snapshot) GetDomainEntries() []*DomainEntryProjection {
	if x != nil {
		return x.DomainEntries
	}
	return nil
}

func (x *Snapshot) GetSnapshotRecordId() uint64 {
	if x != nil {
		return x.SnapshotRecordId
	}
	return 0
}

func (x *Snapshot) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type SnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SnapshotRecordId uint64                 `protobuf:"varint,2,opt,name=snapshot_record_id,json=snapshotRecordId,proto3" json:"snapshot_record_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SnapshotRequest) GetSnapshotRecordId() uint64 {
	if x != nil {
		return x.SnapshotRecordId
	}
	return 0
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ChangeNotification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SnapshotRecordId uint64                 `protobuf:"varint,3,opt,name=snapshot_record_id,json=snapshotRecordId,proto3" json:"snapshot_record_id,omitempty"`
	// Types that are valid to be assigned to Entry:
	//
	//	*ChangeNotification_DnsRecord
	//	*ChangeNotification_DomainEntry
	Entry         isChangeNotification_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeNotification) Reset() {
	*x = ChangeNotification{}
	mi := &file_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNotification) ProtoMessage() {}

func (x *ChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNotification.ProtoReflect.Descriptor instead.
func (*ChangeNotification) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeNotification) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChangeNotification) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChangeNotification) GetSnapshotRecordId() uint64 {
	if x != nil {
		return x.SnapshotRecordId
	}
	return 0
}

func (x *ChangeNotification) GetEntry() isChangeNotification_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *ChangeNotification) GetDnsRecord() *DNSRecord {
	if x != nil {
		if x, ok := x.Entry.(*ChangeNotification_DnsRecord); ok {
			return x.DnsRecord
		}
	}
	return nil
}

func (x *ChangeNotification) GetDomainEntry() *DomainEntryProjection {
	if x != nil {
		if x, ok := x.Entry.(*ChangeNotification_DomainEntry); ok {
			return x.DomainEntry
		}
	}
	return nil
}

type isChangeNotification_Entry interface {
	isChangeNotification_Entry()
}

type ChangeNotification_DnsRecord struct {
	DnsRecord *DNSRecord `protobuf:"bytes,4,opt,name=dns_record,json=dnsRecord,proto3,oneof"`
}

type ChangeNotification_DomainEntry struct {
	DomainEntry *DomainEntryProjection `protobuf:"bytes,5,opt,name=domain_entry,json=domainEntry,proto3,oneof"`
}

func (*ChangeNotification_DnsRecord) isChangeNotification_Entry() {}

func (*ChangeNotification_DomainEntry) isChangeNotification_Entry() {}

type CertificateBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateBundleRequest) Reset() {
	*x = CertificateBundleRequest{}
	mi := &file_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateBundleRequest) ProtoMessage() {}

func (x *CertificateBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateBundleRequest.ProtoReflect.Descriptor instead.
func (*CertificateBundleRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{4}
}

func (x *CertificateBundleRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CertificateBundleRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CertificateBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	TlsCrt        []byte                 `protobuf:"bytes,3,opt,name=tls_crt,json=tlsCrt,proto3" json:"tls_crt,omitempty"`
	TlsKey        []byte                 `protobuf:"bytes,4,opt,name=tls_key,json=tlsKey,proto3" json:"tls_key,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateBundleResponse) Reset() {
	*x = CertificateBundleResponse{}
	mi := &file_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateBundleResponse) ProtoMessage() {}

func (x *CertificateBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateBundleResponse.ProtoReflect.Descriptor instead.
func (*CertificateBundleResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{5}
}

func (x *CertificateBundleResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CertificateBundleResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CertificateBundleResponse) GetTlsCrt() []byte {
	if x != nil {
		return x.TlsCrt
	}
	return nil
}

func (x *CertificateBundleResponse) GetTlsKey() []byte {
	if x != nil {
		return x.TlsKey
	}
	return nil
}

func (x *CertificateBundleResponse) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fqdn          string                 `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	RecordType    string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	RoutingClass  string                 `protobuf:"bytes,4,opt,name=routing_class,json=routingClass,proto3" json:"routing_class,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ValuesJson    string                 `protobuf:"bytes,6,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,7,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Deleted       bool                   `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{6}
}

func (x *DNSRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DNSRecord) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *DNSRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *DNSRecord) GetRoutingClass() string {
	if x != nil {
		return x.RoutingClass
	}
	return ""
}

func (x *DNSRecord) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DNSRecord) GetValuesJson() string {
	if x != nil {
		return x.ValuesJson
	}
	return ""
}

func (x *DNSRecord) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *DNSRecord) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DNSRecord) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ServiceBackendRef struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceNamespace string                 `protobuf:"bytes,2,opt,name=service_namespace,json=serviceNamespace,proto3" json:"service_namespace,omitempty"`
	ServiceName      string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServicePort      uint32                 `protobuf:"varint,4,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceBackendRef) Reset() {
	*x = ServiceBackendRef{}
	mi := &file_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBackendRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBackendRef) ProtoMessage() {}

func (x *ServiceBackendRef) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBackendRef.ProtoReflect.Descriptor instead.
func (*ServiceBackendRef) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceBackendRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceBackendRef) GetServiceNamespace() string {
	if x != nil {
		return x.ServiceNamespace
	}
	return ""
}

func (x *ServiceBackendRef) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceBackendRef) GetServicePort() uint32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

type HTTPRouteProjection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainEndpointId string                 `protobuf:"bytes,2,opt,name=domain_endpoint_id,json=domainEndpointId,proto3" json:"domain_endpoint_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Priority         int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	BackendRef       *ServiceBackendRef     `protobuf:"bytes,6,opt,name=backend_ref,json=backendRef,proto3" json:"backend_ref,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HTTPRouteProjection) Reset() {
	*x = HTTPRouteProjection{}
	mi := &file_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRouteProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRouteProjection) ProtoMessage() {}

func (x *HTTPRouteProjection) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRouteProjection.ProtoReflect.Descriptor instead.
func (*HTTPRouteProjection) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{8}
}

func (x *HTTPRouteProjection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HTTPRouteProjection) GetDomainEndpointId() string {
	if x != nil {
		return x.DomainEndpointId
	}
	return ""
}

func (x *HTTPRouteProjection) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HTTPRouteProjection) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRouteProjection) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *HTTPRouteProjection) GetBackendRef() *ServiceBackendRef {
	if x != nil {
		return x.BackendRef
	}
	return nil
}

type CertificateRevision struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainEndpointId string                 `protobuf:"bytes,2,opt,name=domain_endpoint_id,json=domainEndpointId,proto3" json:"domain_endpoint_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Revision         uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Provider         string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ChallengeType    string                 `protobuf:"bytes,6,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	ArtifactBucket   string                 `protobuf:"bytes,7,opt,name=artifact_bucket,json=artifactBucket,proto3" json:"artifact_bucket,omitempty"`
	ArtifactPrefix   string                 `protobuf:"bytes,8,opt,name=artifact_prefix,json=artifactPrefix,proto3" json:"artifact_prefix,omitempty"`
	Sha256Crt        string                 `protobuf:"bytes,9,opt,name=sha256_crt,json=sha256Crt,proto3" json:"sha256_crt,omitempty"`
	Sha256Key        string                 `protobuf:"bytes,10,opt,name=sha256_key,json=sha256Key,proto3" json:"sha256_key,omitempty"`
	NotBefore        *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter         *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CertificateRevision) Reset() {
	*x = CertificateRevision{}
	mi := &file_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRevision) ProtoMessage() {}

func (x *CertificateRevision) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRevision.ProtoReflect.Descriptor instead.
func (*CertificateRevision) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{9}
}

func (x *CertificateRevision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateRevision) GetDomainEndpointId() string {
	if x != nil {
		return x.DomainEndpointId
	}
	return ""
}

func (x *CertificateRevision) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CertificateRevision) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CertificateRevision) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CertificateRevision) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *CertificateRevision) GetArtifactBucket() string {
	if x != nil {
		return x.ArtifactBucket
	}
	return ""
}

func (x *CertificateRevision) GetArtifactPrefix() string {
	if x != nil {
		return x.ArtifactPrefix
	}
	return ""
}

func (x *CertificateRevision) GetSha256Crt() string {
	if x != nil {
		return x.Sha256Crt
	}
	return ""
}

func (x *CertificateRevision) GetSha256Key() string {
	if x != nil {
		return x.Sha256Key
	}
	return ""
}

func (x *CertificateRevision) GetNotBefore() *timestamp.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateRevision) GetNotAfter() *timestamp.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type DomainEntryProjection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	BackendType      string                 `protobuf:"bytes,3,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	Cert             *CertificateRevision   `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	HttpRoutes       []*HTTPRouteProjection `protobuf:"bytes,5,rep,name=http_routes,json=httpRoutes,proto3" json:"http_routes,omitempty"`
	BindedBackendRef *ServiceBackendRef     `protobuf:"bytes,6,opt,name=binded_backend_ref,json=bindedBackendRef,proto3" json:"binded_backend_ref,omitempty"`
	Deleted          bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DomainEntryProjection) Reset() {
	*x = DomainEntryProjection{}
	mi := &file_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEntryProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEntryProjection) ProtoMessage() {}

func (x *DomainEntryProjection) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEntryProjection.ProtoReflect.Descriptor instead.
func (*DomainEntryProjection) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{10}
}

func (x *DomainEntryProjection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DomainEntryProjection) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DomainEntryProjection) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *DomainEntryProjection) GetCert() *CertificateRevision {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *DomainEntryProjection) GetHttpRoutes() []*HTTPRouteProjection {
	if x != nil {
		return x.HttpRoutes
	}
	return nil
}

func (x *DomainEntryProjection) GetBindedBackendRef() *ServiceBackendRef {
	if x != nil {
		return x.BindedBackendRef
	}
	return nil
}

func (x *DomainEntryProjection) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_replication_proto protoreflect.FileDescriptor

const file_replication_proto_rawDesc = "" +
	"\n" +
	"\x11replication.proto\x12\x13luna.replication.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\bSnapshot\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\vdns_records\x18\x03 \x03(\v2\x1e.luna.replication.v1.DNSRecordR\n" +
	"dnsRecords\x12Q\n" +
	"\x0edomain_entries\x18\x04 \x03(\v2*.luna.replication.v1.DomainEntryProjectionR\rdomainEntries\x12,\n" +
	"\x12snapshot_record_id\x18\x05 \x01(\x04R\x10snapshotRecordId\x12\x12\n" +
	"\x04last\x18\x06 \x01(\bR\x04last\"X\n" +
	"\x0fSnapshotRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\x12snapshot_record_id\x18\x02 \x01(\x04R\x10snapshotRecordId\".\n" +
	"\x13SubscriptionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xb1\x02\n" +
	"\x12ChangeNotification\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12,\n" +
	"\x12snapshot_record_id\x18\x03 \x01(\x04R\x10snapshotRecordId\x12?\n" +
	"\n" +
	"dns_record\x18\x04 \x01(\v2\x1e.luna.replication.v1.DNSRecordH\x00R\tdnsRecord\x12O\n" +
	"\fdomain_entry\x18\x05 \x01(\v2*.luna.replication.v1.DomainEntryProjectionH\x00R\vdomainEntryB\a\n" +
	"\x05entry\"R\n" +
	"\x18CertificateBundleRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"\xaa\x01\n" +
	"\x19CertificateBundleResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x17\n" +
	"\atls_crt\x18\x03 \x01(\fR\x06tlsCrt\x12\x17\n" +
	"\atls_key\x18\x04 \x01(\fR\x06tlsKey\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\fR\fmetadataJson\"\x8c\x02\n" +
	"\tDNSRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\x12#\n" +
	"\rrouting_class\x18\x04 \x01(\tR\froutingClass\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\x12\x1f\n" +
	"\vvalues_json\x18\x06 \x01(\tR\n" +
	"valuesJson\x12\x1f\n" +
	"\vrouting_key\x18\a \x01(\tR\n" +
	"routingKey\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\"\x96\x01\n" +
	"\x11ServiceBackendRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11service_namespace\x18\x02 \x01(\tR\x10serviceNamespace\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_port\x18\x04 \x01(\rR\vservicePort\"\xe8\x01\n" +
	"\x13HTTPRouteProjection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12domain_endpoint_id\x18\x02 \x01(\tR\x10domainEndpointId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12G\n" +
	"\vbackend_ref\x18\x06 \x01(\v2&.luna.replication.v1.ServiceBackendRefR\n" +
	"backendRef\"\xd2\x03\n" +
	"\x13CertificateRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12domain_endpoint_id\x18\x02 \x01(\tR\x10domainEndpointId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12%\n" +
	"\x0echallenge_type\x18\x06 \x01(\tR\rchallengeType\x12'\n" +
	"\x0fartifact_bucket\x18\a \x01(\tR\x0eartifactBucket\x12'\n" +
	"\x0fartifact_prefix\x18\b \x01(\tR\x0eartifactPrefix\x12\x1d\n" +
	"\n" +
	"sha256_crt\x18\t \x01(\tR\tsha256Crt\x12\x1d\n" +
	"\n" +
	"sha256_key\x18\n" +
	" \x01(\tR\tsha256Key\x129\n" +
	"\n" +
	"not_before\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"\xdf\x02\n" +
	"\x15DomainEntryProjection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\fbackend_type\x18\x03 \x01(\tR\vbackendType\x12<\n" +
	"\x04cert\x18\x04 \x01(\v2(.luna.replication.v1.CertificateRevisionR\x04cert\x12I\n" +
	"\vhttp_routes\x18\x05 \x03(\v2(.luna.replication.v1.HTTPRouteProjectionR\n" +
	"httpRoutes\x12T\n" +
	"\x12binded_backend_ref\x18\x06 \x01(\v2&.luna.replication.v1.ServiceBackendRefR\x10bindedBackendRef\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeleted2\xc5\x02\n" +
	"\x12ReplicationService\x12T\n" +
	"\vGetSnapshot\x12$.luna.replication.v1.SnapshotRequest\x1a\x1d.luna.replication.v1.Snapshot0\x01\x12`\n" +
	"\tSubscribe\x12(.luna.replication.v1.SubscriptionRequest\x1a'.luna.replication.v1.ChangeNotification0\x01\x12w\n" +
	"\x16FetchCertificateBundle\x12-.luna.replication.v1.CertificateBundleRequest\x1a..luna.replication.v1.CertificateBundleResponseB?Z=github.com/jabberwocky238/luna-edge/replication/replpb;replpbb\x06proto3"

var (
	file_replication_proto_rawDescOnce sync.Once
	file_replication_proto_rawDescData []byte
)

func file_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)))
	})
	return file_replication_proto_rawDescData
}

var file_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_replication_proto_goTypes = []any{
	(*Snapshot)(nil),                  // 0: luna.replication.v1.Snapshot
	(*SnapshotRequest)(nil),           // 1: luna.replication.v1.SnapshotRequest
	(*SubscriptionRequest)(nil),       // 2: luna.replication.v1.SubscriptionRequest
	(*ChangeNotification)(nil),        // 3: luna.replication.v1.ChangeNotification
	(*CertificateBundleRequest)(nil),  // 4: luna.replication.v1.CertificateBundleRequest
	(*CertificateBundleResponse)(nil), // 5: luna.replication.v1.CertificateBundleResponse
	(*DNSRecord)(nil),                 // 6: luna.replication.v1.DNSRecord
	(*ServiceBackendRef)(nil),         // 7: luna.replication.v1.ServiceBackendRef
	(*HTTPRouteProjection)(nil),       // 8: luna.replication.v1.HTTPRouteProjection
	(*CertificateRevision)(nil),       // 9: luna.replication.v1.CertificateRevision
	(*DomainEntryProjection)(nil),     // 10: luna.replication.v1.DomainEntryProjection
	(*timestamp.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_replication_proto_depIdxs = []int32{
	11, // 0: luna.replication.v1.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: luna.replication.v1.Snapshot.dns_records:type_name -> luna.replication.v1.DNSRecord
	10, // 2: luna.replication.v1.Snapshot.domain_entries:type_name -> luna.replication.v1.DomainEntryProjection
	11, // 3: luna.replication.v1.ChangeNotification.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: luna.replication.v1.ChangeNotification.dns_record:type_name -> luna.replication.v1.DNSRecord
	10, // 5: luna.replication.v1.ChangeNotification.domain_entry:type_name -> luna.replication.v1.DomainEntryProjection
	7,  // 6: luna.replication.v1.HTTPRouteProjection.backend_ref:type_name -> luna.replication.v1.ServiceBackendRef
	11, // 7: luna.replication.v1.CertificateRevision.not_before:type_name -> google.protobuf.Timestamp
	11, // 8: luna.replication.v1.CertificateRevision.not_after:type_name -> google.protobuf.Timestamp
	9,  // 9: luna.replication.v1.DomainEntryProjection.cert:type_name -> luna.replication.v1.CertificateRevision
	8,  // 10: luna.replication.v1.DomainEntryProjection.http_routes:type_name -> luna.replication.v1.HTTPRouteProjection
	7,  // 11: luna.replication.v1.DomainEntryProjection.binded_backend_ref:type_name -> luna.replication.v1.ServiceBackendRef
	1,  // 12: luna.replication.v1.ReplicationService.GetSnapshot:input_type -> luna.replication.v1.SnapshotRequest
	2,  // 13: luna.replication.v1.ReplicationService.Subscribe:input_type -> luna.replication.v1.SubscriptionRequest
	4,  // 14: luna.replication.v1.ReplicationService.FetchCertificateBundle:input_type -> luna.replication.v1.CertificateBundleRequest
	0,  // 15: luna.replication.v1.ReplicationService.GetSnapshot:output_type -> luna.replication.v1.Snapshot
	3,  // 16: luna.replication.v1.ReplicationService.Subscribe:output_type -> luna.replication.v1.ChangeNotification
	5,  // 17: luna.replication.v1.ReplicationService.FetchCertificateBundle:output_type -> luna.replication.v1.CertificateBundleResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_replication_proto_init() }
func file_replication_proto_init() {
	if File_replication_proto != nil {
		return
	}
	file_replication_proto_msgTypes[3].OneofWrappers = []any{
		(*ChangeNotification_DnsRecord)(nil),
		(*ChangeNotification_DomainEntry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_depIdxs,
		MessageInfos:      file_replication_proto_msgTypes,
	}.Build()
	File_replication_proto = out.File
	file_replication_proto_goTypes = nil
	file_replication_proto_depIdxs = nil
}
