apiVersion: v1
kind: Namespace
metadata:
  name: luna-edge
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: luna-edge
spec:
  controllerName: luna-edge.io/ingress-controller
